apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gov-cookiecutter-template
  title: GOV Cookiecutter Template
  description: Template to bootstrap projects using the ONS Innovation govcookiecutter
  annotations:
    github.com/project-slug: ONS-Innovation/govcookiecutter
  tags:
    - cookiecutter
    - govcookiecutter
    - template
  links:
    - url: https://github.com/best-practice-and-impact/govcookiecutter
      title: Original govcookiecutter
      icon: catalog
spec:
  owner: "group:default/spotify-backstage-trial-team"
  type: template
  lifecycle: experimental
  parameters:
    - title: Project Settings
      required:
        - organisation_name
        - repository_hosting_platform
        - organisational_framework
        - project_name
        - overview
        - catalog_owner
      properties:
        repository_hosting_platform:
          title: Repository Hosting Platform
          type: string
          enum:
            - GitHub
            - GitLab
          description: Where is the repository hosted? (GitHub or GitLab)
          default: GitHub
        organisation_name:
          title: Organisation Name
          type: string
          description: What is your GitHub organisation name? (e.g. ONS-Innovation, ONSDigital)
          default: ONS-Innovation
        organisational_framework:
          title: Organisational Framework
          description: What organisational framework are you using? (GDS or N/A)
          type: string
          enum:
            - GDS
            - N/A
        project_name:
          title: Project Name
          type: string
          description: What is your new project name?
        overview:
          title: Description
          type: string
          description: Brief overview of your project (e.g. A project to...)
        catalog_owner:
          title: Catalog Owner
          type: string
          description: Who owns your repository? (user or group)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: User
                metadata.annotations.github.com/user-login: '*'
              - kind: Group
                metadata.annotations.github.com/team-slug: '*'

        project_version:
          title: Project Version
          type: string
          description: Version of your project (e.g. 0.0.1, 1.0.0)
          default: 0.0.1
    - title: Environment Settings
      required:
        - locked_down_environment
        - using_R
      properties:
        locked_down_environment:
          title: Locked Down Environment
          description: Is this a locked down environment? (Yes or No)
          type: string
          enum:
            - No
            - Yes
        using_R:
          title: Using R?
          description: Are you using R for this project? (Yes or No)
          type: string
          enum:
            - No
            - Yes

  steps:
    - id: fetch-entity
      name: Fetch Catalog Entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.catalog_owner }}
    - id: fetch-template
      name: Fetch Cookiecutter Template
      action: fetch:template
      input:
        url: ./project_template
        cookiecutterCompat: true
        values:
          organisation_name: ${{ parameters.organisation_name }}
          repository_hosting_platform: ${{ parameters.repository_hosting_platform }}
          organisational_framework: ${{ parameters.organisational_framework }}
          project_name: ${{ parameters.project_name }}
          overview: ${{ parameters.overview }}
          project_version: ${{ parameters.project_version }}
          locked_down_environment: ${{ parameters.locked_down_environment }}
          using_R: ${{ parameters.using_R }}
          repo_name: ${{ parameters.project_name | lower | replace(' ', '-') | replace('_', '-') }}
          catalog_owner: ${{ parameters.catalog_owner }}
          github_owner: ${{ steps['fetch-entity'].output.entity.metadata.annotations['github.com/team-slug'] or steps['fetch-entity'].output.entity.metadata.annotations['github.com/user-login'] or user.entity.metadata.annotations['github.com/user-login'] }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.organisation_name }}&repo=${{ parameters.project_name }}
        description: ${{ parameters.overview }}
        repoVisibility: public
        defaultBranch: main
        access: ${{ user.entity.metadata.annotations['github.com/user-login'] }}

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
