apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.project_name | lower | replace(' ', '-') | replace('_', '-') }}
  title: {{ cookiecutter.project_name }}
  description: {{ cookiecutter.overview }}
  tags:
    - {{ cookiecutter.organisation_name | lower }}
    - {{ cookiecutter.organisational_framework | lower }}
    - {{ cookiecutter.repository_hosting_platform | lower }}
  links:
    - url: https://codespaces.new/{{ cookiecutter.organisation_name }}/{{ cookiecutter.repo_name }}
      title: Open Development Environment 
      icon: scaffolder
    - url: vscode://vscode.git/clone?url=https://github.com/{{ cookiecutter.organisation_name }}/{{ cookiecutter.repo_name }}.git
      title: Open in Local Visual Studio Code
      icon: scaffolder
  annotations:
    backstage.io/source-template: "gov-cookiecutter-template"

spec:
  type: service
  owner: {{ cookiecutter.catalog_owner | dump }}
  lifecycle: experimental
