apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.project_name | lower | replace(' ', '-') | replace('_', '-') }}
  title: {{ cookiecutter.project_name }}
  description: {{ cookiecutter.overview }}
  tags:
    - {{ cookiecutter.organisation_handle | lower }}
    - {{ cookiecutter.organisational_framework | lower }}
    - {{ cookiecutter.repository_hosting_platform | lower }}
  links:
    - url: https://codespaces.new/{{ cookiecutter.organisation_handle }}/{{ cookiecutter.repo_name }}
      title: Open Development Environment 
      icon: scaffolder
spec:
  type: service
  owner: "group:default/{{ cookiecutter.organisation_handle }}"
  lifecycle: experimental
